# Setup the dataset
dataset: 
  image_dir: age\data\train_images
  csv_path: age\data\meta_train.csv
  batch_size: 64
  image_size: 224
  val_size: 0.2
  oversample: False

# Setup the training parameter
train:
  epochs: 30
  lr: 0.0001
  lr_step: 10
  lr_gamma: 0.5
  model_name: "model"
  checkpoint_dir: 'age\checkpoints'
  patience: 5
  early_stopping: True
  force_cpu: True
  model: "cbam" # [baseline, resnet, cbam]
  weighted_sampling: False
  grad-camp: False  
  grad_camp_sample: 0 
  fitting: True
  plotting: True

# Setup the test parameter
test:
  test_dir: data\test_images
  test_batch_size: 64
  test_image_size: 224
  test_model_path: checkpoints/cbam34_model/best_model.pt
  test_model_name: "cbam34_model"
  prediction_csv_path: data/prediction_submission.csv
  model: "cbam"